use serde::Deserialize;
use serde_json::{Value, json};
use std::fmt::Write as _;
use std::io::{self, IsTerminal, Write};
#[cfg(unix)]
use std::os::unix::process::CommandExt;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::Duration;
use tao_bridge::{TaodBridge, TaodBridgeError};

pub fn run(args: Vec<String>) -> std::process::ExitCode {
    match run_result(args, OutputMode::Human) {
        Ok(()) => std::process::ExitCode::SUCCESS,
        Err(error) => {
            let style = Style::stderr();
            eprintln!("{}", style.red(format!("tao: {error}")));
            std::process::ExitCode::FAILURE
        }
    }
}

pub fn run_for_shell_cd(args: Vec<String>) -> std::process::ExitCode {
    match run_result(args, OutputMode::ShellCd) {
        Ok(()) => std::process::ExitCode::SUCCESS,
        Err(error) => {
            let style = Style::stderr();
            eprintln!("{}", style.red(format!("tao: {error}")));
            std::process::ExitCode::FAILURE
        }
    }
}

pub fn print_help() {
    println!(
        "tao commands\n\nUSAGE:\n  tao new [branch] [--from <ref>] [--print-path] [--json]\n  tao cd [branch] [--print-path]\n  tao local [--print-path]\n  tao handoff [--print-path]\n  tao ls [--json] [--names]\n  tao path [branch]\n  tao rm [branch] [--force] [--yes] [--delete-branch]\n  tao prune\n\nNOTES:\n  taod is the source of truth for workspace/worktree metadata and git operations.\n  Branch names are user-facing. Worktree folders are generated by taod under ~/.tao/worktrees.\n  Handoff moves the current clean branch between a managed worktree and local checkout.\n  A CLI cannot change the parent shell directory by itself; run `eval \"$(tao init zsh)\"`\n  or `tao init zsh --install` to enable auto-cd."
    );
}

pub fn print_worktree_names_for_completion() {
    let Ok(bridge) = TaodBridge::from_default_socket() else {
        return;
    };
    let Ok(workspaces) = list_workspaces(&bridge) else {
        return;
    };
    let Ok(cwd) = std::env::current_dir().and_then(|path| path.canonicalize()) else {
        return;
    };
    let Some(workspace) = best_workspace_match(&workspaces, &cwd) else {
        return;
    };
    let Ok(worktrees) = list_worktrees(&bridge, &workspace.id) else {
        return;
    };

    for worktree in worktrees {
        println!("{}", worktree.branch);
    }
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum OutputMode {
    Human,
    ShellCd,
}

struct Style {
    enabled: bool,
}

impl Style {
    fn stdout() -> Self {
        Self::new(io::stdout().is_terminal())
    }

    fn stderr() -> Self {
        Self::new(io::stderr().is_terminal())
    }

    fn new(is_terminal: bool) -> Self {
        Self {
            enabled: is_terminal && std::env::var_os("NO_COLOR").is_none(),
        }
    }

    fn green(&self, value: impl AsRef<str>) -> String {
        self.paint("32", value.as_ref())
    }

    fn yellow(&self, value: impl AsRef<str>) -> String {
        self.paint("33", value.as_ref())
    }

    fn red(&self, value: impl AsRef<str>) -> String {
        self.paint("31", value.as_ref())
    }

    fn dim(&self, value: impl AsRef<str>) -> String {
        self.paint("2", value.as_ref())
    }

    fn paint(&self, code: &str, value: &str) -> String {
        if self.enabled {
            format!("\x1b[{code}m{value}\x1b[0m")
        } else {
            value.to_string()
        }
    }
}

fn run_result(args: Vec<String>, output_mode: OutputMode) -> Result<(), String> {
    let Some(command) = args.first().map(String::as_str) else {
        print_help();
        return Ok(());
    };

    match command {
        "new" => new_worktree(&args[1..], output_mode),
        "ls" => list_command(&args[1..]),
        "cd" => cd_command(&args[1..], output_mode),
        "local" => local_command(&args[1..], output_mode),
        "handoff" => handoff_command(&args[1..], output_mode),
        "path" => path_command(&args[1..]),
        "rm" => remove_command(&args[1..]),
        "prune" => refresh_command(),
        "help" | "--help" | "-h" => {
            print_help();
            Ok(())
        }
        other => Err(format!("unknown worktree command: {other}")),
    }
}

fn new_worktree(args: &[String], output_mode: OutputMode) -> Result<(), String> {
    let mut branch: Option<String> = None;
    let mut from_ref: Option<String> = None;
    let mut print_path = false;
    let mut json_output = false;

    let mut index = 0;
    while index < args.len() {
        match args[index].as_str() {
            "--from" => {
                index += 1;
                let value = args
                    .get(index)
                    .ok_or_else(|| "--from requires a ref".to_string())?;
                from_ref = Some(value.clone());
            }
            "--print-path" => print_path = true,
            "--json" => json_output = true,
            "--help" | "-h" => {
                println!(
                    "USAGE:\n  tao new [branch] [--from <ref>] [--print-path] [--json]\n\nCreates a taod-managed git worktree. The optional positional argument is the git\nbranch name; when omitted taod generates a branch name. The folder path is\nalways generated by taod."
                );
                return Ok(());
            }
            value if value.starts_with('-') => {
                return Err(format!("unknown option for new: {value}"));
            }
            value => {
                if branch.is_some() {
                    return Err("new accepts at most one branch name".to_string());
                }
                branch = Some(value.to_string());
            }
        }
        index += 1;
    }

    let bridge = connected_bridge()?;
    let workspace = current_workspace(&bridge)?;
    let mut request = json!({
        "type": "worktree.create",
        "id": request_id("worktree-create"),
        "workspaceId": workspace.id,
    });
    if let Some(branch) = &branch {
        request["branch"] = json!(branch);
        request["title"] = json!(branch);
        request["targetBranch"] = json!(branch);
    }
    if let Some(from_ref) = &from_ref {
        request["baseBranch"] = json!(from_ref);
        request["startPoint"] = json!(from_ref);
    }

    let response = bridge.request_value(&request)?;
    ensure_ok(&response)?;
    let worktree = worktree_from_response(&response)?;

    if output_mode == OutputMode::ShellCd {
        eprint_created_worktree(&worktree);
        println!("{}", worktree.path.display());
    } else if json_output {
        println!("{}", selected_worktree_json(&worktree));
    } else if print_path {
        println!("{}", worktree.path.display());
    } else {
        print_created_worktree(&worktree);
    }

    Ok(())
}

fn list_command(args: &[String]) -> Result<(), String> {
    let mut json_output = false;
    let mut names = false;
    for arg in args {
        match arg.as_str() {
            "--json" => json_output = true,
            "--names" => names = true,
            "--help" | "-h" => {
                println!("USAGE:\n  tao ls [--json] [--names]");
                return Ok(());
            }
            value => return Err(format!("unknown option for ls: {value}")),
        }
    }

    let bridge = connected_bridge()?;
    let workspace = current_workspace(&bridge)?;
    let worktrees = list_worktrees(&bridge, &workspace.id)?;
    if names {
        for worktree in worktrees {
            println!("{}", worktree.branch);
        }
    } else if json_output {
        print_worktrees_json(&worktrees);
    } else {
        print_worktree_table(&worktrees);
    }
    Ok(())
}

fn cd_command(args: &[String], output_mode: OutputMode) -> Result<(), String> {
    let mut branch: Option<String> = None;
    let mut print_path = false;
    for arg in args {
        match arg.as_str() {
            "--print-path" => print_path = true,
            "--help" | "-h" => {
                println!(
                    "USAGE:\n  tao cd [branch] [--print-path]\n\nEnters a worktree by branch name only. With no branch, Tao uses the current\nlocal git branch."
                );
                return Ok(());
            }
            value if value.starts_with('-') => {
                return Err(format!("unknown option for cd: {value}"));
            }
            value => {
                if branch.is_some() {
                    return Err("cd accepts at most one branch".to_string());
                }
                branch = Some(value.to_string());
            }
        }
    }

    let bridge = connected_bridge()?;
    let workspace = current_workspace(&bridge)?;
    let branch = match branch {
        Some(branch) => branch,
        None => current_git_branch()?,
    };

    let worktrees = list_worktrees(&bridge, &workspace.id)?;
    let worktree = resolve_worktree_branch(&branch, &worktrees)?;
    if output_mode == OutputMode::ShellCd {
        eprint_selected_worktree(&worktree);
        println!("{}", worktree.path.display());
    } else if print_path {
        println!("{}", worktree.path.display());
    } else {
        print_selected_worktree(&worktree);
    }
    Ok(())
}

fn local_command(args: &[String], output_mode: OutputMode) -> Result<(), String> {
    let mut print_path = false;
    for arg in args {
        match arg.as_str() {
            "--print-path" => print_path = true,
            "--help" | "-h" => {
                println!(
                    "USAGE:\n  tao local [--print-path]\n\nPrints or enters the local workspace checkout for the current Tao workspace."
                );
                return Ok(());
            }
            value => return Err(format!("unknown option for local: {value}")),
        }
    }

    let bridge = connected_bridge()?;
    let workspace = current_workspace(&bridge)?;
    if output_mode == OutputMode::ShellCd {
        eprint_local_workspace(&workspace);
        println!("{}", workspace.root_path.display());
    } else if print_path {
        println!("{}", workspace.root_path.display());
    } else {
        print_local_workspace(&workspace);
    }
    Ok(())
}

fn handoff_command(args: &[String], output_mode: OutputMode) -> Result<(), String> {
    let mut print_path = false;
    for arg in args {
        match arg.as_str() {
            "--print-path" => print_path = true,
            "--yes" | "-y" => {}
            "--help" | "-h" => {
                println!(
                    "USAGE:\n  tao handoff [--print-path]\n\nMoves the current branch between a taod-managed worktree and the local workspace\ncheckout. taod owns the git handoff and refuses a dirty source checkout. Shell\nintegration cds to the destination checkout."
                );
                return Ok(());
            }
            value if value.starts_with('-') => {
                return Err(format!("unknown option for handoff: {value}"));
            }
            _ => return Err("handoff does not accept a branch argument".to_string()),
        }
    }

    let bridge = connected_bridge()?;
    let cwd = std::env::current_dir()
        .map_err(|error| format!("failed to read current directory: {error}"))?
        .canonicalize()
        .map_err(|error| format!("failed to canonicalize current directory: {error}"))?;
    let response = bridge.request_value(&json!({
        "type": "worktree.handoff",
        "id": request_id("worktree-handoff"),
        "path": cwd.to_string_lossy(),
    }))?;
    ensure_ok(&response)?;
    let handoff = handoff_from_response(&response)?;

    if output_mode == OutputMode::ShellCd {
        eprint_handoff(&handoff);
        println!("{}", handoff.destination.display());
    } else if print_path {
        println!("{}", handoff.destination.display());
    } else {
        print_handoff(&handoff);
    }
    Ok(())
}

fn path_command(args: &[String]) -> Result<(), String> {
    let mut query: Option<String> = None;
    for arg in args {
        match arg.as_str() {
            "--help" | "-h" => {
                println!("USAGE:\n  tao path [branch]");
                return Ok(());
            }
            value if value.starts_with('-') => {
                return Err(format!("unknown option for path: {value}"));
            }
            value => {
                if query.is_some() {
                    return Err("path accepts at most one branch".to_string());
                }
                query = Some(value.to_string());
            }
        }
    }

    let bridge = connected_bridge()?;
    let workspace = current_workspace(&bridge)?;
    let worktree = choose_worktree(&bridge, &workspace.id, query.as_deref())?;
    println!("{}", worktree.path.display());
    Ok(())
}

fn remove_command(args: &[String]) -> Result<(), String> {
    let mut query: Option<String> = None;
    let mut force = false;
    let mut yes = false;
    let mut delete_branch = false;

    for arg in args {
        match arg.as_str() {
            "--force" | "-f" => force = true,
            "--yes" | "-y" => yes = true,
            "--delete-branch" => delete_branch = true,
            "--help" | "-h" => {
                println!(
                    "USAGE:\n  tao rm [branch] [--force] [--yes] [--delete-branch]\n\nBranch matches the branch of a taod-managed worktree."
                );
                return Ok(());
            }
            value if value.starts_with('-') => {
                return Err(format!("unknown option for rm: {value}"));
            }
            value => {
                if query.is_some() {
                    return Err("rm accepts at most one branch".to_string());
                }
                query = Some(value.to_string());
            }
        }
    }

    let bridge = connected_bridge()?;
    let workspace = current_workspace(&bridge)?;
    let worktree = choose_worktree(&bridge, &workspace.id, query.as_deref())?;
    if current_dir_is_under(&worktree.path)? {
        return Err("refusing to remove the current worktree".to_string());
    }

    if !yes && io::stdin().is_terminal() {
        eprint!("Remove worktree {}? [y/N] ", worktree.path.display());
        io::stderr().flush().map_err(|error| error.to_string())?;
        let mut answer = String::new();
        io::stdin()
            .read_line(&mut answer)
            .map_err(|error| format!("failed to read confirmation: {error}"))?;
        if !matches!(answer.trim(), "y" | "Y" | "yes" | "YES") {
            let style = Style::stderr();
            eprintln!("{}", style.yellow("! Remove cancelled"));
            return Ok(());
        }
    }

    let response = bridge.request_value(&json!({
        "type": "worktree.remove",
        "id": request_id("worktree-remove"),
        "worktreeId": worktree.id,
        "force": force,
        "deleteBranch": delete_branch,
    }))?;
    ensure_ok(&response)?;

    let style = Style::stdout();
    println!("{}", style.green("✓ Removed worktree"));
    println!();
    println!("  branch  {}", worktree.branch);
    println!(
        "  path    {}",
        style.dim(worktree.path.display().to_string())
    );
    Ok(())
}

fn refresh_command() -> Result<(), String> {
    let bridge = connected_bridge()?;
    let workspace = current_workspace(&bridge)?;
    refresh_workspace(&bridge, &workspace.id)?;
    let style = Style::stdout();
    println!("{}", style.green("✓ Refreshed taod worktree state"));
    Ok(())
}

#[derive(Clone, Debug, Deserialize)]
struct Workspace {
    id: String,
    root_path: PathBuf,
    #[serde(default)]
    worktrees: Vec<Worktree>,
}

#[derive(Clone, Debug, Deserialize)]
struct Worktree {
    id: String,
    folder_name: String,
    path: PathBuf,
    branch: String,
    state: String,
}

#[derive(Debug, Deserialize)]
struct HandoffResponse {
    branch: String,
    source_path: PathBuf,
    destination_path: PathBuf,
}

struct HandoffResult {
    branch: String,
    source: PathBuf,
    destination: PathBuf,
}

fn connected_bridge() -> Result<TaodBridge, String> {
    let bridge = TaodBridge::from_default_socket()?;
    ensure_daemon_running(&bridge)?;
    Ok(bridge)
}

fn ensure_daemon_running(bridge: &TaodBridge) -> Result<(), String> {
    match ping_daemon(bridge) {
        Ok(()) => return Ok(()),
        Err(error) if is_daemon_unreachable_error(&error) => {}
        Err(error) => return Err(error.to_string()),
    }

    let binary = find_taod_binary().ok_or_else(|| {
        format!(
            "taod is not running and no taod binary was found (socket: {}). Build it with `pnpm --filter @tao/daemon build` or set TAOD_PATH.",
            bridge.socket_path().display()
        )
    })?;
    let mut command = Command::new(&binary);
    command
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null());
    #[cfg(unix)]
    // SAFETY: this closure only calls async-signal-safe `setsid` and returns an
    // OS error if it fails. It runs in the child after fork and before exec to
    // detach taod from the CLI's terminal session.
    unsafe {
        command.pre_exec(|| {
            if setsid() == -1 {
                Err(io::Error::last_os_error())
            } else {
                Ok(())
            }
        });
    }
    command
        .spawn()
        .map_err(|error| format!("failed to start taod at {}: {error}", binary.display()))?;

    let mut last_error = None;
    for _ in 0..40 {
        std::thread::sleep(Duration::from_millis(75));
        match ping_daemon(bridge) {
            Ok(()) => return Ok(()),
            Err(error) if is_daemon_unreachable_error(&error) => {
                last_error = Some(error.to_string());
            }
            Err(error) => return Err(error.to_string()),
        }
    }

    let mut message = format!(
        "timed out waiting for taod to start at {}",
        bridge.socket_path().display()
    );
    if let Some(error) = last_error {
        message.push_str(&format!(": {error}"));
    }
    Err(message)
}

fn is_daemon_unreachable_error(error: &PingError) -> bool {
    matches!(
        error,
        PingError::Bridge(TaodBridgeError::Closed)
            | PingError::Bridge(TaodBridgeError::Connect {
                kind: io::ErrorKind::NotFound | io::ErrorKind::ConnectionRefused,
                ..
            })
    )
}

#[cfg(unix)]
unsafe extern "C" {
    fn setsid() -> i32;
}

#[derive(Debug)]
enum PingError {
    Bridge(TaodBridgeError),
    Daemon(String),
}

impl std::fmt::Display for PingError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Bridge(error) => write!(formatter, "{error}"),
            Self::Daemon(error) => write!(formatter, "{error}"),
        }
    }
}

fn ping_daemon(bridge: &TaodBridge) -> Result<(), PingError> {
    let response = bridge
        .request_value_typed(&json!({
            "type": "ping",
            "id": request_id("ping"),
        }))
        .map_err(PingError::Bridge)?;
    ensure_ok(&response).map_err(PingError::Daemon)
}

fn find_taod_binary() -> Option<PathBuf> {
    let exe = if cfg!(windows) { "taod.exe" } else { "taod" };
    let mut candidates = Vec::new();
    if let Some(path) = std::env::var_os("TAOD_PATH")
        && !path.is_empty()
    {
        candidates.push(PathBuf::from(path));
    }
    if let Ok(cwd) = std::env::current_dir() {
        candidates.push(
            cwd.join("apps")
                .join("daemon")
                .join("zig-out")
                .join("bin")
                .join(exe),
        );
        candidates.push(
            cwd.join("..")
                .join("daemon")
                .join("zig-out")
                .join("bin")
                .join(exe),
        );
        candidates.push(
            cwd.join("..")
                .join("..")
                .join("apps")
                .join("daemon")
                .join("zig-out")
                .join("bin")
                .join(exe),
        );
    }
    if let Ok(current_exe) = std::env::current_exe()
        && let Some(parent) = current_exe.parent()
    {
        candidates.push(parent.join(exe));
        candidates.push(parent.join("taod"));
        candidates.push(
            parent
                .join("..")
                .join("daemon")
                .join("zig-out")
                .join("bin")
                .join(exe),
        );
    }
    candidates.into_iter().find(|path| path.is_file())
}

fn current_workspace(bridge: &TaodBridge) -> Result<Workspace, String> {
    let cwd = std::env::current_dir()
        .map_err(|error| format!("failed to read current directory: {error}"))?
        .canonicalize()
        .map_err(|error| format!("failed to canonicalize current directory: {error}"))?;

    let workspaces = list_workspaces(bridge)?;
    if let Some(workspace) = best_workspace_match(&workspaces, &cwd) {
        return Ok(workspace.clone());
    }

    add_workspace(bridge, &cwd)
}

fn best_workspace_match(workspaces: &[Workspace], cwd: &Path) -> Option<Workspace> {
    let mut best: Option<(usize, Workspace)> = None;
    for workspace in workspaces {
        let mut score = 0;
        if path_contains(&workspace.root_path, cwd) {
            score = score.max(workspace.root_path.components().count());
        }
        for worktree in &workspace.worktrees {
            if path_contains(&worktree.path, cwd) {
                score = score.max(worktree.path.components().count());
            }
        }
        if score > best.as_ref().map(|(score, _)| *score).unwrap_or(0) {
            best = Some((score, workspace.clone()));
        }
    }
    best.map(|(_, workspace)| workspace)
}

fn list_workspaces(bridge: &TaodBridge) -> Result<Vec<Workspace>, String> {
    let response = bridge.request_value(&json!({
        "type": "workspace.list",
        "id": request_id("workspace-list"),
    }))?;
    ensure_ok(&response)?;
    value_array::<Workspace>(&response, "workspaces")
}

fn add_workspace(bridge: &TaodBridge, path: &Path) -> Result<Workspace, String> {
    let response = bridge.request_value(&json!({
        "type": "workspace.add",
        "id": request_id("workspace-add"),
        "rootPath": path.to_string_lossy(),
    }))?;
    ensure_ok(&response)?;
    value_object::<Workspace>(&response, "workspace")
}

fn list_worktrees(bridge: &TaodBridge, workspace_id: &str) -> Result<Vec<Worktree>, String> {
    let response = bridge.request_value(&json!({
        "type": "worktree.list",
        "id": request_id("worktree-list"),
        "workspaceId": workspace_id,
    }))?;
    ensure_ok(&response)?;
    value_array::<Worktree>(&response, "worktrees")
}

fn refresh_workspace(bridge: &TaodBridge, workspace_id: &str) -> Result<(), String> {
    let response = bridge.request_value(&json!({
        "type": "worktree.refresh",
        "id": request_id("worktree-refresh"),
        "workspaceId": workspace_id,
    }))?;
    ensure_ok(&response)
}

fn choose_worktree(
    bridge: &TaodBridge,
    workspace_id: &str,
    query: Option<&str>,
) -> Result<Worktree, String> {
    let worktrees = list_worktrees(bridge, workspace_id)?;
    if let Some(query) = query {
        return resolve_worktree(query, &worktrees);
    }
    if worktrees.is_empty() {
        return Err("no taod-managed worktrees found for this workspace".to_string());
    }
    if io::stdin().is_terminal() && command_exists("fzf") {
        return choose_worktree_with_fzf(&worktrees);
    }
    if worktrees.len() == 1 {
        return Ok(worktrees[0].clone());
    }
    let style = Style::stderr();
    eprintln!(
        "{}",
        style.yellow("! Multiple worktrees found; provide a query or install fzf")
    );
    eprintln!();
    eprint_worktree_table(&worktrees);
    Err("provide a query, or install fzf for interactive selection".to_string())
}

fn resolve_worktree(query: &str, worktrees: &[Worktree]) -> Result<Worktree, String> {
    let mut stderr = io::stderr();
    resolve_worktree_with_diagnostics(query, worktrees, &mut stderr)
}

fn resolve_worktree_with_diagnostics(
    query: &str,
    worktrees: &[Worktree],
    diagnostics: &mut impl Write,
) -> Result<Worktree, String> {
    let mut exact_matches = Vec::new();
    let mut partial_matches = Vec::new();
    for worktree in worktrees {
        let path = worktree.path.to_string_lossy();
        let is_exact = worktree.id == query
            || worktree.branch == query
            || worktree.folder_name == query
            || path == query;
        let is_partial = worktree.branch.contains(query)
            || worktree.folder_name.contains(query)
            || path.contains(query);

        if is_exact {
            exact_matches.push(worktree.clone());
        } else if is_partial {
            partial_matches.push(worktree.clone());
        }
    }

    let mut matches = if exact_matches.is_empty() {
        partial_matches
    } else {
        exact_matches
    };

    match matches.len() {
        0 => Err(format!("no worktree matches {query:?}")),
        1 => Ok(matches.remove(0)),
        _ => {
            let style = Style::stderr();
            let _ = writeln!(
                diagnostics,
                "{}",
                style.yellow(format!("! Query {query:?} matched multiple worktrees"))
            );
            let _ = writeln!(diagnostics);
            let _ = write_worktree_table(diagnostics, &matches);
            let _ = writeln!(diagnostics, "\nTry an exact branch, folder, id, or path.");
            Err(format!("query {query:?} matched multiple worktrees"))
        }
    }
}

fn resolve_worktree_branch(branch: &str, worktrees: &[Worktree]) -> Result<Worktree, String> {
    let mut matches: Vec<Worktree> = worktrees
        .iter()
        .filter(|worktree| worktree.branch == branch)
        .cloned()
        .collect();

    match matches.len() {
        0 => Err(format!("no worktree matches branch {branch:?}")),
        1 => Ok(matches.remove(0)),
        _ => {
            let style = Style::stderr();
            eprintln!(
                "{}",
                style.yellow(format!("! Branch {branch:?} matched multiple worktrees"))
            );
            eprintln!();
            eprint_worktree_table(&matches);
            Err(format!("branch {branch:?} matched multiple worktrees"))
        }
    }
}

fn choose_worktree_with_fzf(worktrees: &[Worktree]) -> Result<Worktree, String> {
    let mut input = String::new();
    for (index, worktree) in worktrees.iter().enumerate() {
        writeln!(
            input,
            "{}\t{}\t{}\t{}",
            index,
            worktree.branch,
            worktree.state,
            worktree.path.display()
        )
        .map_err(|error| error.to_string())?;
    }

    let mut child = Command::new("fzf")
        .arg("--delimiter")
        .arg("\t")
        .arg("--with-nth")
        .arg("2,3,4")
        .arg("--prompt")
        .arg("tao> ")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .map_err(|error| format!("failed to start fzf: {error}"))?;

    if let Some(stdin) = child.stdin.as_mut() {
        stdin
            .write_all(input.as_bytes())
            .map_err(|error| format!("failed to write fzf choices: {error}"))?;
    }

    let output = child
        .wait_with_output()
        .map_err(|error| format!("failed to wait for fzf: {error}"))?;
    if !output.status.success() {
        return Err("no worktree selected".to_string());
    }

    let selection = String::from_utf8(output.stdout)
        .map_err(|error| format!("fzf returned non-utf8 output: {error}"))?;
    let index = selection
        .split('\t')
        .next()
        .ok_or_else(|| "fzf returned an empty selection".to_string())?
        .trim()
        .parse::<usize>()
        .map_err(|error| format!("fzf returned an invalid selection: {error}"))?;
    worktrees
        .get(index)
        .cloned()
        .ok_or_else(|| "fzf selected an unknown worktree".to_string())
}

fn print_worktree_table(worktrees: &[Worktree]) {
    let mut stdout = io::stdout();
    write_worktree_table(&mut stdout, worktrees).expect("write worktree table");
}

fn print_created_worktree(worktree: &Worktree) {
    let style = Style::stdout();
    println!("{}", style.green("✓ Created worktree"));
    println!();
    print_worktree_summary(worktree, &style);
    println!();
    println!("Next:");
    println!(
        "  cd {}",
        shell_quote(worktree.path.to_string_lossy().as_ref())
    );
    println!();
    println!("For auto-cd:");
    println!("  tao init zsh --install   # or: bash/fish");
}

fn eprint_created_worktree(worktree: &Worktree) {
    let style = Style::stderr();
    eprintln!("{}", style.green("✓ Created worktree"));
    eprintln!();
    eprint_worktree_summary(worktree, &style);
}

fn print_selected_worktree(worktree: &Worktree) {
    let style = Style::stdout();
    println!("{}", style.green("✓ Selected worktree"));
    println!();
    print_worktree_summary(worktree, &style);
    println!();
    println!("Next:");
    println!(
        "  cd {}",
        shell_quote(worktree.path.to_string_lossy().as_ref())
    );
    println!();
    println!("For auto-cd:");
    println!("  tao init zsh --install   # or: bash/fish");
}

fn eprint_selected_worktree(worktree: &Worktree) {
    let style = Style::stderr();
    eprintln!("{}", style.green("✓ Entering worktree"));
    eprintln!();
    eprint_worktree_summary(worktree, &style);
}

fn print_local_workspace(workspace: &Workspace) {
    let style = Style::stdout();
    println!("{}", style.green("✓ Selected local workspace"));
    println!();
    println!(
        "  path    {}",
        style.dim(workspace.root_path.display().to_string())
    );
    println!();
    println!("Next:");
    println!(
        "  cd {}",
        shell_quote(workspace.root_path.to_string_lossy().as_ref())
    );
}

fn eprint_local_workspace(workspace: &Workspace) {
    let style = Style::stderr();
    eprintln!("{}", style.green("✓ Entering local workspace"));
    eprintln!();
    eprintln!(
        "  path    {}",
        style.dim(workspace.root_path.display().to_string())
    );
}

fn print_handoff(handoff: &HandoffResult) {
    let style = Style::stdout();
    println!("{}", style.green("✓ Handed off worktree branch"));
    println!();
    print_handoff_summary(handoff, &style);
    println!();
    println!("Next:");
    println!(
        "  cd {}",
        shell_quote(handoff.destination.to_string_lossy().as_ref())
    );
}

fn eprint_handoff(handoff: &HandoffResult) {
    let style = Style::stderr();
    eprintln!("{}", style.green("✓ Handed off worktree branch"));
    eprintln!();
    eprint_handoff_summary(handoff, &style);
}

fn print_handoff_summary(handoff: &HandoffResult, style: &Style) {
    println!("  branch   {}", handoff.branch);
    println!(
        "  from     {}",
        style.dim(handoff.source.display().to_string())
    );
    println!(
        "  to       {}",
        style.dim(handoff.destination.display().to_string())
    );
}

fn eprint_handoff_summary(handoff: &HandoffResult, style: &Style) {
    eprintln!("  branch   {}", handoff.branch);
    eprintln!(
        "  from     {}",
        style.dim(handoff.source.display().to_string())
    );
    eprintln!(
        "  to       {}",
        style.dim(handoff.destination.display().to_string())
    );
}

fn print_worktree_summary(worktree: &Worktree, style: &Style) {
    println!("  branch  {}", worktree.branch);
    println!(
        "  path    {}",
        style.dim(worktree.path.display().to_string())
    );
}

fn eprint_worktree_summary(worktree: &Worktree, style: &Style) {
    eprintln!("  branch  {}", worktree.branch);
    eprintln!(
        "  path    {}",
        style.dim(worktree.path.display().to_string())
    );
}

fn eprint_worktree_table(worktrees: &[Worktree]) {
    let mut stderr = io::stderr();
    let _ = write_worktree_table(&mut stderr, worktrees);
}

fn write_worktree_table(output: &mut impl Write, worktrees: &[Worktree]) -> io::Result<()> {
    let style = Style::new(io::stdout().is_terminal() || io::stderr().is_terminal());
    let branch_width = worktrees
        .iter()
        .map(|worktree| worktree.branch.len())
        .chain(std::iter::once("branch".len()))
        .max()
        .unwrap_or("branch".len());
    let state_width = worktrees
        .iter()
        .map(|worktree| worktree.state.len())
        .chain(std::iter::once("state".len()))
        .max()
        .unwrap_or("state".len());

    writeln!(
        output,
        "{}",
        style.green(format!(
            "{} worktree{}",
            worktrees.len(),
            if worktrees.len() == 1 { "" } else { "s" }
        ))
    )?;
    writeln!(output)?;

    let current = std::env::current_dir().ok();
    let current_index = current.as_deref().and_then(|cwd| {
        worktrees
            .iter()
            .position(|worktree| path_contains(&worktree.path, cwd))
    });

    for (index, worktree) in worktrees.iter().enumerate() {
        let marker = if Some(index) == current_index {
            style.green("●")
        } else {
            style.dim("○")
        };
        writeln!(
            output,
            "{}  {:<branch_width$}  {:<state_width$}  {}",
            marker,
            worktree.branch,
            state_label(&style, &worktree.state),
            style.dim(compact_path(&worktree.path))
        )?;
    }
    Ok(())
}

fn state_label(style: &Style, state: &str) -> String {
    match state {
        "active" => style.green(state),
        "error" => style.red(state),
        _ => style.yellow(state),
    }
}

fn compact_path(path: &Path) -> String {
    let path_text = path.to_string_lossy();
    if let Some(home) = std::env::var_os("HOME").filter(|value| !value.is_empty()) {
        let home = PathBuf::from(home);
        if let Ok(stripped) = path.strip_prefix(&home) {
            return format!("~/{}", stripped.display());
        }
    }
    path_text.to_string()
}

fn print_worktrees_json(worktrees: &[Worktree]) {
    let value: Vec<Value> = worktrees.iter().map(selected_worktree_json).collect();
    println!(
        "{}",
        serde_json::to_string_pretty(&value).expect("worktree json serialization cannot fail")
    );
}

fn selected_worktree_json(worktree: &Worktree) -> Value {
    json!({
        "id": worktree.id,
        "folder_name": worktree.folder_name,
        "branch": worktree.branch,
        "path": worktree.path.to_string_lossy(),
        "state": worktree.state,
    })
}

fn worktree_from_response(response: &Value) -> Result<Worktree, String> {
    value_object(response, "worktree")
}

fn handoff_from_response(response: &Value) -> Result<HandoffResult, String> {
    let response: HandoffResponse = serde_json::from_value(response.clone())
        .map_err(|error| format!("invalid taod handoff response: {error}"))?;
    Ok(HandoffResult {
        branch: response.branch,
        source: response.source_path,
        destination: response.destination_path,
    })
}

fn value_object<T: for<'de> Deserialize<'de>>(response: &Value, key: &str) -> Result<T, String> {
    let value = response
        .get(key)
        .cloned()
        .ok_or_else(|| format!("taod response is missing {key}"))?;
    serde_json::from_value(value).map_err(|error| format!("invalid taod {key} response: {error}"))
}

fn value_array<T: for<'de> Deserialize<'de>>(
    response: &Value,
    key: &str,
) -> Result<Vec<T>, String> {
    let value = response
        .get(key)
        .cloned()
        .ok_or_else(|| format!("taod response is missing {key}"))?;
    serde_json::from_value(value).map_err(|error| format!("invalid taod {key} response: {error}"))
}

fn ensure_ok(response: &Value) -> Result<(), String> {
    if response.get("ok").and_then(Value::as_bool) == Some(true) {
        return Ok(());
    }
    let message = response
        .get("error_message")
        .or_else(|| response.get("errorMessage"))
        .and_then(Value::as_str)
        .unwrap_or("taod request failed");
    let code = response
        .get("error_code")
        .or_else(|| response.get("errorCode"))
        .and_then(Value::as_str);
    if let Some(code) = code {
        Err(format!("{message} ({code})"))
    } else {
        Err(message.to_string())
    }
}

fn request_id(prefix: &str) -> String {
    use std::sync::atomic::{AtomicU64, Ordering};
    static NEXT_ID: AtomicU64 = AtomicU64::new(0);
    let next = NEXT_ID.fetch_add(1, Ordering::Relaxed) + 1;
    format!("cli-{prefix}-{}-{next}", std::process::id())
}

fn command_exists(command: &str) -> bool {
    Command::new("sh")
        .arg("-c")
        .arg("command -v \"$1\" >/dev/null 2>&1")
        .arg("sh")
        .arg(command)
        .status()
        .map(|status| status.success())
        .unwrap_or(false)
}

fn current_dir_is_under(path: &Path) -> Result<bool, String> {
    let cwd = std::env::current_dir()
        .map_err(|error| format!("failed to read current directory: {error}"))?
        .canonicalize()
        .map_err(|error| format!("failed to canonicalize current directory: {error}"))?;
    Ok(path_contains(path, &cwd))
}

fn current_git_branch() -> Result<String, String> {
    let cwd = std::env::current_dir()
        .map_err(|error| format!("failed to read current directory: {error}"))?;
    current_git_branch_at(&cwd)
}

fn current_git_branch_at(path: &Path) -> Result<String, String> {
    let output = Command::new("git")
        .arg("-C")
        .arg(path)
        .arg("branch")
        .arg("--show-current")
        .output()
        .map_err(|error| format!("failed to run git: {error}"))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        let message = stderr.trim();
        return if message.is_empty() {
            Err("failed to read current git branch".to_string())
        } else {
            Err(format!("failed to read current git branch: {message}"))
        };
    }

    let branch = String::from_utf8(output.stdout)
        .map_err(|error| format!("git returned non-utf8 branch name: {error}"))?
        .trim()
        .to_string();
    if branch.is_empty() {
        Err("current git checkout is detached; pass a branch to `tao cd`".to_string())
    } else {
        Ok(branch)
    }
}

fn path_contains(parent: &Path, child: &Path) -> bool {
    let parent = parent
        .canonicalize()
        .unwrap_or_else(|_| parent.to_path_buf());
    let child = child.canonicalize().unwrap_or_else(|_| child.to_path_buf());
    child == parent || child.starts_with(parent)
}

fn shell_quote(value: &str) -> String {
    if value.is_empty() {
        return "''".to_string();
    }
    if value.chars().all(|character| {
        character.is_ascii_alphanumeric() || matches!(character, '/' | '.' | '_' | '-' | ':')
    }) {
        value.to_string()
    } else {
        format!("'{}'", value.replace('\'', "'\\''"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn path_contains_child() {
        let cwd = std::env::current_dir().expect("current dir");
        let parent = cwd.parent().expect("current dir has parent");
        assert!(path_contains(parent, &cwd));
    }

    #[test]
    fn path_contains_rejects_sibling_prefix() {
        assert!(!path_contains(
            Path::new("/tmp/repo"),
            Path::new("/tmp/repo2")
        ));
    }

    #[test]
    fn resolve_worktree_matches_exact_branch() {
        let selected = resolve_worktree(
            "feature/login",
            &[
                test_worktree("worktree-1", "feature/login", "/tmp/tao/worktrees/one"),
                test_worktree("worktree-2", "feature/login-old", "/tmp/tao/worktrees/two"),
            ],
        )
        .expect("exact branch resolves");

        assert_eq!(selected.id, "worktree-1");
    }

    #[test]
    fn resolve_worktree_reports_ambiguous_query() {
        let mut diagnostics = Vec::new();
        let error = resolve_worktree_with_diagnostics(
            "feature",
            &[
                test_worktree("worktree-1", "feature/login", "/tmp/tao/worktrees/one"),
                test_worktree("worktree-2", "feature/logout", "/tmp/tao/worktrees/two"),
            ],
            &mut diagnostics,
        )
        .expect_err("ambiguous query fails");

        assert!(error.contains("matched multiple worktrees"));
        assert!(!diagnostics.is_empty());
    }

    #[test]
    fn resolve_worktree_branch_requires_exact_branch() {
        let selected = resolve_worktree_branch(
            "feature/login",
            &[
                test_worktree("worktree-1", "feature/login", "/tmp/tao/worktrees/one"),
                test_worktree("worktree-2", "feature/login-old", "/tmp/tao/worktrees/two"),
            ],
        )
        .expect("exact branch resolves");

        assert_eq!(selected.id, "worktree-1");
    }

    #[test]
    fn resolve_worktree_branch_rejects_partial_branch() {
        let error = resolve_worktree_branch(
            "feature",
            &[
                test_worktree("worktree-1", "feature/login", "/tmp/tao/worktrees/one"),
                test_worktree("worktree-2", "feature/logout", "/tmp/tao/worktrees/two"),
            ],
        )
        .expect_err("partial branch does not resolve");

        assert!(error.contains("no worktree matches branch"));
    }

    #[test]
    fn best_workspace_match_checks_known_worktree_paths() {
        let workspace = Workspace {
            id: "workspace-1".to_string(),
            root_path: PathBuf::from("/tmp/repo"),
            worktrees: vec![test_worktree(
                "worktree-1",
                "feature/login",
                "/tmp/home/.tao/worktrees/repo/generated",
            )],
        };

        let selected = best_workspace_match(
            &[workspace],
            Path::new("/tmp/home/.tao/worktrees/repo/generated/src"),
        )
        .expect("worktree path maps back to workspace");

        assert_eq!(selected.id, "workspace-1");
    }

    #[test]
    fn ensure_ok_reports_taod_error_code() {
        let error = ensure_ok(&json!({
            "ok": false,
            "error_code": "worktree-dirty",
            "error_message": "worktree has uncommitted changes",
        }))
        .expect_err("error response fails");

        assert_eq!(error, "worktree has uncommitted changes (worktree-dirty)");
    }

    #[test]
    fn daemon_unreachable_errors_are_startable() {
        assert!(is_daemon_unreachable_error(&connect_ping_error(
            std::io::ErrorKind::NotFound
        )));
        assert!(is_daemon_unreachable_error(&connect_ping_error(
            std::io::ErrorKind::ConnectionRefused
        )));
        assert!(is_daemon_unreachable_error(&PingError::Bridge(
            TaodBridgeError::Closed
        )));
    }

    #[test]
    fn daemon_protocol_errors_are_not_startable() {
        assert!(!is_daemon_unreachable_error(&PingError::Bridge(
            TaodBridgeError::UnsupportedPlatform
        )));
        assert!(!is_daemon_unreachable_error(&connect_ping_error(
            std::io::ErrorKind::PermissionDenied
        )));
        assert!(!is_daemon_unreachable_error(&PingError::Bridge(
            TaodBridgeError::Decode("expected value at line 1 column 1".to_string())
        )));
    }

    #[test]
    fn shell_quote_quotes_spaces() {
        assert_eq!(shell_quote("/tmp/a b"), "'/tmp/a b'");
    }

    fn test_worktree(id: &str, branch: &str, path: &str) -> Worktree {
        Worktree {
            id: id.to_string(),
            folder_name: format!("folder-{id}"),
            path: PathBuf::from(path),
            branch: branch.to_string(),
            state: "active".to_string(),
        }
    }

    fn connect_ping_error(kind: std::io::ErrorKind) -> PingError {
        PingError::Bridge(TaodBridgeError::Connect {
            socket_path: PathBuf::from("/tmp/taod.sock"),
            kind,
            message: "connect failed".to_string(),
        })
    }
}
